name: ESDE GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world!
        run: date
      # ADD SOME CUSTOM UNIQUE CODE HERE!!!!
      - name: Printing job status
        run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Check the branch convention usage
        uses: duart38/branch-convention-check@v2.1.0
        with:
          standard_branch_check: '(\b(?:fix|feat|ci|patch)\b(-([0-9])+|)\b(?:-[a-z]{3,})+\b)'
          ignore_branch_check: '(\b(?:testing)\b(-([0-9])+|)\b(?:-[a-z]{3,})+\b)'
          ignore: 'main' #
